### ISSUE TITLE
ModuleNotFoundError: No module named 'core' / Thylakoid system building w/ martini3

### ISSUE THREAD

**Issue by palbanese** [Tsjerk/Insane#69]
Hi, 

i have been trying to use the script on both a WSL2 (Linux subsystem) and installed through anaconda (both via pip). I get the following error in both cases. I sourced the folder to the path, but also get the same error when running the script directly from the folder. 

Traceback (most recent call last):
  File "c:\users\pasca\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\pasca\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\pasca\AppData\Roaming\Python\Python37\Scripts\insane.exe\__main__.py", line 4, in <module>
  File "C:\Users\pasca\AppData\Roaming\Python\Python37\site-packages\insane\__init__.py", line 37, in <module>
    from core import *
ModuleNotFoundError: No module named 'core'

What I am trying to build is a system for the plant thylakoid membrane, it is already available in Martini2 ff (http://cgmartini.nl/index.php/all-files-needed-for-the-simulation-of-a-thylakoid-membrane). I do have the protein model produced with martinize3. The name of the lipids however changed (I cannot fine corresponding definitions in the "_lipid_data.py". 

I ran the following command, guessing the lipid types with the new names: 
insane -f m13_cg.pdb -o system.gro -p system.top -x 200 -y 300 -z 200 -l OPPG:5 -l JPPG:10 -l FPMG:5 -l DFMG:25 -l FPSG:5 -l FPGG:35 -l DFGG:15 -center -sol W -salt 0.01

In this zip folder the AA and the CG models.
[mode13_Hok.zip](https://github.com/Tsjerk/Insane/files/7114603/mode13_Hok.zip)

Thanks, 
Pascal

**Comment by MaximZaigraev** [comment]
Hi!
There is actually an issue with INSANE program. You should manually **replace** "from core import *" with "**from .core import ***" in **insane_init.py** (in your case File "C:\Users\pasca\AppData\Roaming\Python\Python37\site-packages\insane_init.py")

**Comment by MaximZaigraev** [comment]
https://stackoverflow.com/questions/35330964/no-module-named-core-when-using-pyping-for-python-3

**Comment by andreashlarsen** [comment]
Hi. 
I still get that error you mention above after installing insane with pip: 
------------------
> sudo pip install insane
> insane
Traceback (most recent call last):
  File "/opt/anaconda3/bin/insane", line 5, in <module>
    from insane.cli import cli
  File "/opt/anaconda3/lib/python3.7/site-packages/insane/__init__.py", line 37, in <module>
    from core import *
ModuleNotFoundError: No module named 'core'
----------------
same error on my mac and linux computers.
I can see that "from core import *" has been been changed to "from .core import *" in insane/__init_.py on Github, but maybe the pip version is not updated? It looks like pip version is 1.0:
------------------
> pip show insane
Name: insane
Version: 1.0rc1
------------------
whereas Github version is 1.1. 

can anyone (dis)confirm? and maybe update the pip version if this is the case? 

thanks for a super-useful script! 

/Andreas

**Comment by PaulMac12** [comment]
Hello,

I am having the following issue with the tutorial command:

./insane -l POPC -d 10 -dz 7 -sol W -o bilayer.gro -p topol.top

I get this error:

File "./insane/__main__.py", line 3, in <module>
  File "<frozen zipimport>", line 259, in load_module
  File "./insane/insane/__init__.py", line 37, in <module>
ModuleNotFoundError: No module named 'core'

I tried pip install core, but was unsuccessful.

ERROR: Could not find a version that satisfies the requirement core (from versions: none)
ERROR: No matching distribution found for core

Is there any way to successfully run insane?

Thank you.

**Comment by ma3ke** [comment]
> whereas Github version is 1.1.
> 
> can anyone (dis)confirm? and maybe update the pip version if this is the case?

We would indeed like to release new versions on PyPI again, so installing _insane_ through `pip` provides a recent version.

Currently, the [PyPI version is 1.2](https://pypi.org/project/insane/1.2.0/), but the repository contains many nice recent additions. Work is underway to cut a new release and publish these on PyPI as well :)

---

@andreashlarsen, I'm curious whether these issues persist. I could have a try at them, but since we are four years along at this point, circumstances may have changed of course. Feel free to let us know.

**Comment by ma3ke** [comment]
If any of these issues persist, we can open a new issue for each specific case and work through it there.
